	<title>
	Welcome
	</title>
	<?php
	session_start();
	include("includes/adminloginheader.php");
	if(!$_SESSION['admin_email']){
		header("location:adminlogin.php");
	  }
	?>
	<br></br>
	<br></br>

		<div class="container">
			<div class="col-sm-6 col-sm-offset-3" styele="box-shadow:2px 2px 2px 2px gray;">
				<?php
					$conn=new mysqli("localhost","root","","votingsystem_db");
 					$id=$_GET['id'];
 					$select="select * from cdt_id_request_tbl where id='$id'";
 					$run=$conn->query ($select);

					if ($run->num_rows>0){
						while ($row=$run->fetch_array()){
							 
							$name=$row['name'];
							$id=$row['id'];
							$email=$row['email'];
							$constituency=$row['constituency'];
							$party=$row['party'];
							$elections_name=$row['elections_name'];
						}

						$rand=rand();
						$rand;

						?>

						<form method="post">
							<div class="form-group">
								<label for="exampleInputName"><font size="3" color="#ffffff">Full Name:</font></label>
								<input type="text"  class="form-control" id="exampleInputName" name="name" placeholder="Enter Name"
								required  readonly value="<?php echo $name;?>">
							</div>

							<div class="form-group">
								<label for="exampleInputName"><font size="3" color="#ffffff">ID:</font></label>
								<input type="text"  class="form-control" id="exampleInputName" name="id" placeholder="Enter ID"
								required  readonly value="<?php echo $id;?>">
							</div>

							<div class="form-group">
						        <label for="exampleInputName"><font size="3" color="#ffffff">Email:</font></label>
						        <input type="text"  class="form-control" id="exampleInputName" name="email" placeholder="Enter Email"
								required  readonly value="<?php echo $email;?>"> 
							</div>

							<div class="form-group">
						        <label for="exampleInputName"><font size="3" color="#ffffff">Constituency:</font></label>
						        <input type="text"  class="form-control" id="exampleInputName" name="constituency" placeholder="Enter Constituency"
								required  readonly value="<?php echo $constituency;?>"> 
							</div>

							<div class="form-group">
						        <label for="exampleInputName"><font size="3" color="#ffffff">Party:</font></label>
						        <input type="text"  class="form-control" id="exampleInputName" name="party" placeholder="Enter Party"
								required  readonly value="<?php echo $party;?>"> 
							</div>

							<div class="form-group">
						        <label for="exampleInputName"><font size="3" color="#ffffff">Election Name:</font></label>
						        <input type="text"  class="form-control" id="exampleInputName" name="elections_name" placeholder="Enter Elections Name"
								required  readonly value="<?php echo $elections_name;?>"> 
							</div>

							<div class="form-group">
						        <label for="exampleInputName"><font size="3" color="#ffffff">ID Generated by System:</font></label>
						        <input type="text"  class="form-control" id="exampleInputName" name="id_generated" placeholder="Enter name"
								required  readonly value="<?php echo $rand;?>"> 
							</div>

							<br>

							<div class="form-group">
								<input type="submit" name="approve" value="Approve" class="form-control btn btn-success">
							</div>

							<br>

							<div class="form-group">
								<input type="submit" name="reject" value="Reject" class="form-control btn btn-success">
							</div>
						</form>

						<?php

					}
					else{
					 	echo "Record Not Found";
					}

				?>
			</div>
			<div class="col-sm-6">

			</div>
		</div>
</body>
</html>

<?php
if(isset($_POST['approve'])){
	$name=$_POST['name'];
	$id=$_POST['id'];
	$email=$_POST['email'];
	$constituency=$_POST['constituency'];
	$party=$_POST['party'];
	$elections_name=$_POST['elections_name'];
	$id_generated=$_POST['id_generated'];

	$update="update user_db set cdt_id_generated='$id_generated'where user_id='$id'";
	$run=$conn->query($update);
	if($run){
		echo "<script>alert('Request Was Approved')</script>";
	}

	$delete="delete from cdt_id_request_tbl where id='$id'";
	$del=$conn->query($delete);

	if($del){
		echo "<script>alert('cdt_id_request_tbl Table is Updated')</script>";
	}

	$insert="insert into candidate_db (name,id,email,constituency,party,election_name) values ('$name','$id','$email','$constituency','$party','$elections_name')";
	$ins=$conn->query($insert);

	if($ins){
		echo "<script>alert('candidate_db is Updated')</script>";
		echo "<script>window.location.href='cdtidrequest.php'</script>";
	}
}

elseif(isset($_POST['reject'])){
	$name=$_POST['name'];
	$id=$_POST['id'];
	$email=$_POST['email'];
	$constituency=$_POST['constituency'];
	$party=$_POST['party'];
	$id_generated=$_POST['id_generated'];

	$delete="delete from cdt_id_request_tbl where id='$id'";
	$del=$conn->query($delete);

	if($del){
		echo "<script>alert('Request Was Rejected')</script>";
		echo "<script>window.location.href='cdtidrequest.php'</script>";
	}
}
