<title>
Welcome</title>
<?php
session_start();
include("includes/loginheader.php");
if(!$_SESSION['user_id']){
	header("location:login.php");
  }
?>
<br></br>
<center>
	<img src="image/election.png" class="img img-responsive" style="width:500px;height:500px;"> 
</center>
<br></br>
<div class="container">
	<div class="col-md-6 col-md-offset-3">
		<form method="post">
			<div class="form-group">
        		<label for="exampleInputName"><font size="3" color="#ffffff">Your ID Generated by admin:</font></label>
        		<input type="text" class="form-control" id="exampleInputName" name="user_id" placeholder="Enter your ID"
				required >
			</div>
		
			<div class="form-group">
				<label for="password"><font size="3" color="#ffffff">Password</font></label>
				<input type="password" name="user_password" class="form-control" placeholder="Enter password"
				required >
			</div>

			<br>

			<div class="form-group">
				<button type="submit" class="btn btn-success btn-block" name="login"><font size="3" color="#ffffff">Enter Voting Area</font></button>
			</div>
		</form>
	</div> 
</div>
	
<?php
require("includes/db.php");
if(isset($_POST['login'])){
	$user_id=$_POST['user_id'];
	$user_password=$_POST['user_password'];
	$select="select * from user_db where user_password='$user_password' and user_id_generated='$user_id'";
	$run=$conn->query($select);
	if($run->num_rows>0){
		while($row=$run->fetch_array()){
        $_SESSION['user_id_generated']=$user_id_generated=$row['user_id_generated'];
	 	}
	 	header('location:vote.php');
	}
	else{
		echo "Your ID or Password is invalid";
	}
}
?> 