	<title>
	Welcome
	</title>
	<?php
	session_start();
	include("includes/adminloginheader.php");
	if(!$_SESSION['admin_email']){
		header("location:adminlogin.php");
	  }
	?>
	<br></br>
	<br></br>

<div class="container">
			<div class="col-sm-6 col-sm-offset-3" styele="box-shadow:2px 2px 2px 2px gray;">
<?php


 
$conn=new mysqli("localhost","root","","votingsystem_db");
 $id=$_GET['id'];
 $select="select * from id_request_tbl where id='$id'";
 $run=$conn->query ($select);
 if ($run->num_rows>0){
	 while ($row=$run->fetch_array()){
		 
		 $user_id=$row['user_id'];
		 $user_constituency=$row['user_constituency'];
	 }
	 

	 $rand=rand();
	 $rand;
		
	 
		 ?>
	 
	 <form method="post">
	 <div class="form-group">
        <label for="exampleInputName"><font size="3" color="#ffffff">User ID:</font></label>
        <input type="text"  class="form-control" id="exampleInputName" name="user_id" placeholder="Enter name"
		required  readonly value="<?php echo $user_id;?>">
		</div>
		<div class="form-group">
        <label for="exampleInputName"><font size="3" color="#ffffff">User Constituency:</font></label>
        <input type="text"  class="form-control" id="exampleInputName" name="user_constituency" placeholder="Enter name"
		required  readonly value="<?php echo $user_constituency;?>"> 
		</div>
		<div class="form-group">
        <label for="exampleInputName"><font size="3" color="#ffffff">User ID Generated by System:</font></label>
        <input type="text"  class="form-control" id="exampleInputName" name="user_id_generated" placeholder="Enter name"
		required  readonly value="<?php echo $rand;?>"> 
		</div>
		<br>
		<div class="form-group">
			<input type="submit" name="update" value="Update User ID" class="form-control btn btn-success">
	 
	 </form>
	 
	 	 
	 <?php
	 
	 }
	 else{
	 	echo "Record Not Found";
	 }
 
?>

</div>

<div class="col-sm-6">

</div>
</div>
</body>
</html>

<?php
if(isset($_POST['update'])){
	 $user_id=$_POST['user_id'];
	 $user_id_generated=$_POST['user_id_generated'];
	 $update="update user_db set user_id_generated='$user_id_generated'where user_id=$user_id";
	 $run=$conn->query($update);
	 if($run){
	 	
	 	$delete="delete from id_request_tbl where user_id='$user_id'";
	 	$del=$conn->query($delete);
	 	if($del){
	 		echo "<script>alert('Update Successfully and Deleted')</script>";
	 		echo "<script>window.location.href='idrequest.php'</script>";



	 	}
	 }
	 else{
	 	echo "<script>alert('Something went wrong! Error')</script>";
	 }
}





?>